[header]
path = "gpl-header.txt"

[files]
excludes = [
    # Test files
    "*.toml",
    "*.md",
    ".github/**",
    ".github/",
    "*.whl",
    "*.lock",
    "assets",
    "scripts",
]

[git]
file_attrs = 'auto'
ignore = 'auto'

[props]
inception_year = 2020
project_name = "BlenderDMX"
