class DMX_Icon:

    BREAK = 'DECORATE'
    FIXTURE = 'LIGHT'
    FIXTURE_BATCH = 'LIGHTPROBE_GRID'
    
    UNIVERSE = 'EMPTY_AXIS'
    GDTF_PROFILE = 'WORDWRAP_ON'
    
    BUILD = 'MOD_WIREFRAME'
    REMOVE = 'TRASH'
    CONFIGURE = 'TOOL_SETTINGS'
    CREATE_LIGHTS = 'LIGHT_SPOT'

    SELECT_ALL = 'SELECT_EXTEND'
    SELECT_INVERT = 'SELECT_SUBTRACT'
    SELECT_EVERY_OTHER = 'SELECT_INTERSECT'
    DESELECT_ALL = 'SELECT_SET'