name: Check if code is formatted
on: [ push, pull_request ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          version: "latest"
          args: --version
      - uses: astral-sh/ruff-action@v3
        with:
          version: "latest"
          args: format --check
